
export const products = [
    {
        title: 'Adidas Response',
        description: 'Corré contra el reloj con estas zapatillas de running adidas. Traen un exterior de malla transpirable y un cuello acolchado Geofit que sujeta el tobillo. Bounce en el talón y Bounce+ a lo largo del pie aumentan la sensación de amortiguación para una mayor velocidad y comodidad. La suela de caucho proporciona un agarre excelente, así que atrévete a dejar atrás el asfalto.',
        price: 23599,
        stock: 10,
        category: 'running',
        img: '/assets/response.png',
    },
    {
        title: 'Adidas Ligra 7 ',
        description: 'Corré contra el reloj con estas zapatillas de running adidas. Traen un exterior de malla transpirable y un cuello acolchado Geofit que sujeta el tobillo. Bounce en el talón y Bounce+ a lo largo del pie aumentan la sensación de amortiguación para una mayor velocidad y comodidad. La suela de caucho proporciona un agarre excelente, así que atrévete a dejar atrás el asfalto.',
        price: 20999,
        stock: 15,
        category: 'botines',
        img: '/assets/ligra7.png',
    },
    {
        title: 'Adidas Gamecourt 2',
        description: 'Corré contra el reloj con estas zapatillas de running adidas. Traen un exterior de malla transpirable y un cuello acolchado Geofit que sujeta el tobillo. Bounce en el talón y Bounce+ a lo largo del pie aumentan la sensación de amortiguación para una mayor velocidad y comodidad. La suela de caucho proporciona un agarre excelente, así que atrévete a dejar atrás el asfalto.',
        price: 17959,
        stock: 9,
        category: 'tenis',
        img: '/assets/gamecurt2.png',
    },
    {
        title: 'Adidas Predator Edge 3',
        description: 'Corré contra el reloj con estas zapatillas de running adidas. Traen un exterior de malla transpirable y un cuello acolchado Geofit que sujeta el tobillo. Bounce en el talón y Bounce+ a lo largo del pie aumentan la sensación de amortiguación para una mayor velocidad y comodidad. La suela de caucho proporciona un agarre excelente, así que atrévete a dejar atrás el asfalto.',
        price: 25999,
        stock: 17,
        category: 'botines',
        img: '/assets/predatoredge3.png',
    },
    {
        title: 'Adidas Predator Edge 4',
        description: 'Corré contra el reloj con estas zapatillas de running adidas. Traen un exterior de malla transpirable y un cuello acolchado Geofit que sujeta el tobillo. Bounce en el talón y Bounce+ a lo largo del pie aumentan la sensación de amortiguación para una mayor velocidad y comodidad. La suela de caucho proporciona un agarre excelente, así que atrévete a dejar atrás el asfalto.',
        price: 17999,
        stock: 23,
        category: 'botines',
        img: '/assets/predatoredge4.png',
    },
    {
        title: 'Adidas Coreracer',
        description: 'Corré contra el reloj con estas zapatillas de running adidas. Traen un exterior de malla transpirable y un cuello acolchado Geofit que sujeta el tobillo. Bounce en el talón y Bounce+ a lo largo del pie aumentan la sensación de amortiguación para una mayor velocidad y comodidad. La suela de caucho proporciona un agarre excelente, así que atrévete a dejar atrás el asfalto.',
        price: 15999,
        stock: 20,
        category: 'running',
        img: '/assets/coreracer.png',
    },
    {
        title: 'Adidas Supernova',
        description: 'Corré contra el reloj con estas zapatillas de running adidas. Traen un exterior de malla transpirable y un cuello acolchado Geofit que sujeta el tobillo. Bounce en el talón y Bounce+ a lo largo del pie aumentan la sensación de amortiguación para una mayor velocidad y comodidad. La suela de caucho proporciona un agarre excelente, así que atrévete a dejar atrás el asfalto.',
        price: 28299,
        stock: 11,
        category: 'running',
        img: '/assets/supernova.png',
    },
    {
        title: 'Adidas Court Flash',
        description: 'Corré contra el reloj con estas zapatillas de running adidas. Traen un exterior de malla transpirable y un cuello acolchado Geofit que sujeta el tobillo. Bounce en el talón y Bounce+ a lo largo del pie aumentan la sensación de amortiguación para una mayor velocidad y comodidad. La suela de caucho proporciona un agarre excelente, así que atrévete a dejar atrás el asfalto.',
        price: 25099,
        stock: 13,
        category: 'tenis',
        img: '/assets/courtflash.png',
    },
    {
        title: 'Adidas Galaxy 6',
        description: 'Corré contra el reloj con estas zapatillas de running adidas. Traen un exterior de malla transpirable y un cuello acolchado Geofit que sujeta el tobillo. Bounce en el talón y Bounce+ a lo largo del pie aumentan la sensación de amortiguación para una mayor velocidad y comodidad. La suela de caucho proporciona un agarre excelente, así que atrévete a dejar atrás el asfalto.',
        price: 15099,
        stock: 30,
        category: 'running',
        img: '/assets/galaxy6.png',
    },
    {
        title: 'Adidas Galaxy Run',
        description: 'Corré contra el reloj con estas zapatillas de running adidas. Traen un exterior de malla transpirable y un cuello acolchado Geofit que sujeta el tobillo. Bounce en el talón y Bounce+ a lo largo del pie aumentan la sensación de amortiguación para una mayor velocidad y comodidad. La suela de caucho proporciona un agarre excelente, así que atrévete a dejar atrás el asfalto.',
        price: 23999,
        stock: 6,
        category: 'running',
        img: '/assets/galaxyrun.png',
    },
    {
        title: 'Adidas Supernova 2',
        description: 'Corré contra el reloj con estas zapatillas de running adidas. Traen un exterior de malla transpirable y un cuello acolchado Geofit que sujeta el tobillo. Bounce en el talón y Bounce+ a lo largo del pie aumentan la sensación de amortiguación para una mayor velocidad y comodidad. La suela de caucho proporciona un agarre excelente, así que atrévete a dejar atrás el asfalto.',
        price: 30999,
        stock: 13,
        category: 'running',
        img: '/assets/supernova2.png',
    },
    {
        title: 'Adidas Duramo10',
        description: 'Corré contra el reloj con estas zapatillas de running adidas. Traen un exterior de malla transpirable y un cuello acolchado Geofit que sujeta el tobillo. Bounce en el talón y Bounce+ a lo largo del pie aumentan la sensación de amortiguación para una mayor velocidad y comodidad. La suela de caucho proporciona un agarre excelente, así que atrévete a dejar atrás el asfalto.',
        price: 19099,
        stock: 19,
        category: 'running',
        img: '/assets/duramo10.png',
    },
    {
        title: 'Adidas x900',
        description: 'Corré contra el reloj con estas zapatillas de running adidas. Traen un exterior de malla transpirable y un cuello acolchado Geofit que sujeta el tobillo. Bounce en el talón y Bounce+ a lo largo del pie aumentan la sensación de amortiguación para una mayor velocidad y comodidad. La suela de caucho proporciona un agarre excelente, así que atrévete a dejar atrás el asfalto.',
        price: 29999,
        stock: 9,
        category: 'running',
        img: '/assets/adidasx900.png',
    },
    {
        title: 'Adidas Goletto',
        description: 'Corré contra el reloj con estas zapatillas de running adidas. Traen un exterior de malla transpirable y un cuello acolchado Geofit que sujeta el tobillo. Bounce en el talón y Bounce+ a lo largo del pie aumentan la sensación de amortiguación para una mayor velocidad y comodidad. La suela de caucho proporciona un agarre excelente, así que atrévete a dejar atrás el asfalto.',
        price: 14000,
        stock: 4,
        category: 'botines',
        img: '/assets/goletto.png',
    },
    {
        title: 'Adidas Predator F4.',
        description: 'Corré contra el reloj con estas zapatillas de running adidas. Traen un exterior de malla transpirable y un cuello acolchado Geofit que sujeta el tobillo. Bounce en el talón y Bounce+ a lo largo del pie aumentan la sensación de amortiguación para una mayor velocidad y comodidad. La suela de caucho proporciona un agarre excelente, así que atrévete a dejar atrás el asfalto.',
        price: 9000,
        stock: 8,
        category: 'botines',
        img: '/assets/predatorf4.png',
    },
]