
export const products = [
    {
        id: 1,
        title: 'Adidas Response',
        description: 'Corré contra el reloj con estas zapatillas de running adidas. Traen un exterior de malla transpirable y un cuello acolchado Geofit que sujeta el tobillo. Bounce en el talón y Bounce+ a lo largo del pie aumentan la sensación de amortiguación para una mayor velocidad y comodidad. La suela de caucho proporciona un agarre excelente, así que atrévete a dejar atrás el asfalto.',
        price: 23.599,
        stock: 10,
        category: 'running',
        img: '/assets/response.png',
    },
    {
        id: 2,
        title: 'Adidas Ligra 7 ',
        description: 'Corré contra el reloj con estas zapatillas de running adidas. Traen un exterior de malla transpirable y un cuello acolchado Geofit que sujeta el tobillo. Bounce en el talón y Bounce+ a lo largo del pie aumentan la sensación de amortiguación para una mayor velocidad y comodidad. La suela de caucho proporciona un agarre excelente, así que atrévete a dejar atrás el asfalto.',
        price: 20.999,
        stock: 15,
        category: 'botines',
        img: '/assets/ligra7.png',
    },
    {
        id: 3,
        title: 'Adidas Gamecourt 2',
        description: 'Corré contra el reloj con estas zapatillas de running adidas. Traen un exterior de malla transpirable y un cuello acolchado Geofit que sujeta el tobillo. Bounce en el talón y Bounce+ a lo largo del pie aumentan la sensación de amortiguación para una mayor velocidad y comodidad. La suela de caucho proporciona un agarre excelente, así que atrévete a dejar atrás el asfalto.',
        price: 17.959,
        stock: 20,
        category: 'tenis',
        img: '/assets/gamecurt2.png',
    },
    {
        id: 4,
        title: 'Adidas Predator Edge 3',
        description: 'Corré contra el reloj con estas zapatillas de running adidas. Traen un exterior de malla transpirable y un cuello acolchado Geofit que sujeta el tobillo. Bounce en el talón y Bounce+ a lo largo del pie aumentan la sensación de amortiguación para una mayor velocidad y comodidad. La suela de caucho proporciona un agarre excelente, así que atrévete a dejar atrás el asfalto.',
        price: 25.999,
        stock: 25,
        category: 'botines',
        img: '/assets/predatoredge3.png',
    },
    {
        id: 5,
        title: 'Adidas Predator Edge 4',
        description: 'Corré contra el reloj con estas zapatillas de running adidas. Traen un exterior de malla transpirable y un cuello acolchado Geofit que sujeta el tobillo. Bounce en el talón y Bounce+ a lo largo del pie aumentan la sensación de amortiguación para una mayor velocidad y comodidad. La suela de caucho proporciona un agarre excelente, así que atrévete a dejar atrás el asfalto.',
        price: 17.999,
        stock: 25,
        category: 'botines',
        img: '/assets/predatoredge4.png',
    },
    {
        id: 6,
        title: 'Adidas Coreracer',
        description: 'Corré contra el reloj con estas zapatillas de running adidas. Traen un exterior de malla transpirable y un cuello acolchado Geofit que sujeta el tobillo. Bounce en el talón y Bounce+ a lo largo del pie aumentan la sensación de amortiguación para una mayor velocidad y comodidad. La suela de caucho proporciona un agarre excelente, así que atrévete a dejar atrás el asfalto.',
        price: 15.999,
        stock: 20,
        category: 'running',
        img: '/assets/coreracer.png',
    },
    {
        id: 7,
        title: 'Adidas Supernova',
        description: 'Corré contra el reloj con estas zapatillas de running adidas. Traen un exterior de malla transpirable y un cuello acolchado Geofit que sujeta el tobillo. Bounce en el talón y Bounce+ a lo largo del pie aumentan la sensación de amortiguación para una mayor velocidad y comodidad. La suela de caucho proporciona un agarre excelente, así que atrévete a dejar atrás el asfalto.',
        price: 28.299,
        stock: 20,
        category: 'running',
        img: '/assets/supernova.png',
    },
    {
        id: 8,
        title: 'Adidas Court Flash',
        description: 'Corré contra el reloj con estas zapatillas de running adidas. Traen un exterior de malla transpirable y un cuello acolchado Geofit que sujeta el tobillo. Bounce en el talón y Bounce+ a lo largo del pie aumentan la sensación de amortiguación para una mayor velocidad y comodidad. La suela de caucho proporciona un agarre excelente, así que atrévete a dejar atrás el asfalto.',
        price: 25.099,
        stock: 20,
        category: 'tenis',
        img: '/assets/courtflash.png',
    },
]